### ISSUE TITLE
请问可以把拼音换成小鹤双拼吗

### ISSUE THREAD

**Issue by byron-off** [GuoBinyong/wubixinshiji#8]
要是不行也没关系，就是好奇，平时用的是双拼，觉得很舒服

**Comment by byron-off** [comment]
我找到了
`wubixinshiji.schema.yaml` 文件修改如下：

```yaml
# ... ...

schema:

  #... ...

  dependencies:
    - double_pinyin_flypy

#... ...

reverse_lookup:
  dictionary: rime_mint           # 小鹤双拼用的是rime_mint词典
  prism: double_pinyin_flypy  # 多方案共用一个词库时，为避免冲突，需要用 prism 指定一个名字，此处为 double_pinyin_flypy
  prefix: "z"

#... ...

```
